export const docsConfig = {
  gettingStarted: [
    { name: "Introduction", href: "/docs/introduction" },
    { name: "Installation", href: "/docs/installation" },
  ],
  frameworkGuides: [
    { name: "NextJS", href: "/docs/frameworks/nextjs" },
    { name: "Vite", href: "/docs/frameworks/vite" },
    { name: "Laravel", href: "/docs/frameworks/laravel" },
    { name: "CDN", href: "/docs/frameworks/cdn" },
  ],
  animations: [
    { name: "Playground", href: "/docs/animations" },
  ],
  templates: [
    { 
      name: "Landing Page", 
      href: "/templates/landing-page",
      description: "Modern landing page with hero section, features, and CTA",
      image: "/templates/landing-page.png",
      repository: "https://github.com/auralix-ui/template-landing-page"
    },
    { 
      name: "Dashboard", 
      href: "/templates/dashboard",
      description: "Admin dashboard with stats, charts, and data tables",
      image: "/templates/dashboard.png",
      repository: "https://github.com/auralix-ui/template-dashboard"
    },
    { 
      name: "Blog", 
      href: "/templates/blog",
      description: "Clean blog template with posts grid and article layout",
      image: "/templates/blog.png",
      repository: "https://github.com/auralix-ui/template-blog"
    },
    { 
      name: "Portfolio", 
      href: "/templates/portfolio",
      description: "Creative portfolio to showcase your work and projects",
      image: "/templates/portfolio.png",
      repository: "https://github.com/auralix-ui/template-portfolio"
    },
  ],
  components: [
    { name: "Accordion", href: "/components/accordion" },
    { name: "Alert", href: "/components/alert" },
    { name: "AnimatedBeam", href: "/components/animated-beam" },
    { name: "AnimatedGradientText", href: "/components/animated-gradient-text" },
    { name: "AuroraBackground", href: "/components/aurora-background" },
    { name: "Badge", href: "/components/badge" },
    { name: "BlurText", href: "/components/blur-text" },
    { name: "BorderBeam", href: "/components/border-beam" },
    { name: "Breadcrumb", href: "/components/breadcrumb" },
    { name: "Button", href: "/components/button" },
    { name: "Calendar", href: "/components/calendar" },
    { name: "Card", href: "/components/card" },
    { name: "Carousel", href: "/components/carousel" },
    { name: "Checkbox", href: "/components/checkbox" },
    { name: "Combobox", href: "/components/combobox" },
    { name: "Confetti", href: "/components/confetti" },
    { name: "DatePicker", href: "/components/date-picker" },
    { name: "Dialog", href: "/components/dialog" },
    { name: "Divider", href: "/components/divider" },
    { name: "Dock", href: "/components/dock" },
    { name: "DotPattern", href: "/components/dot-pattern" },
    { name: "Dropdown", href: "/components/dropdown" },
    { name: "EmptyState", href: "/components/empty-state" },
    { name: "ExpandableCard", href: "/components/expandable-card" },
    { name: "FileTree", href: "/components/file-tree" },
    { name: "FlipCard", href: "/components/flip-card" },
    { name: "FlipWords", href: "/components/flip-words" },
    { name: "Form", href: "/components/form" },
    { name: "GlassCard", href: "/components/glass-card" },
    { name: "Globe", href: "/components/globe" },
    { name: "GridPattern", href: "/components/grid-pattern" },
    { name: "HoverCard", href: "/components/hover-card" },
    { name: "Input", href: "/components/input" },
    { name: "InputOTP", href: "/components/input-otp" },
    { name: "IPhoneMockup", href: "/components/iphone-mockup" },
    { name: "Kbd", href: "/components/kbd" },
    { name: "MacBookMockup", href: "/components/macbook-mockup" },
    { name: "MagicCard", href: "/components/magic-card" },
    { name: "Marquee", href: "/components/marquee" },
    { name: "MeteorMeteors", href: "/components/meteor-meteors" },
    { name: "Meteors", href: "/components/meteors" },
    { name: "Modal", href: "/components/modal" },
    { name: "NeonButton", href: "/components/neon-button" },
    { name: "NumberField", href: "/components/number-field" },
    { name: "Pagination", href: "/components/pagination" },
    { name: "Particles", href: "/components/particles" },
    { name: "Popover", href: "/components/popover" },
    { name: "Progress", href: "/components/progress" },
    { name: "Radio", href: "/components/radio" },
    { name: "Resizable", href: "/components/resizable" },
    { name: "Ripple", href: "/components/ripple" },
    { name: "SafariMockup", href: "/components/safari-mockup" },
    { name: "SearchField", href: "/components/search-field" },
    { name: "Select", href: "/components/select" },
    { name: "ShinyText", href: "/components/shiny-text" },
    { name: "Sheet", href: "/components/sheet" },
    { name: "Skeleton", href: "/components/skeleton" },
    { name: "Slider", href: "/components/slider" },
    { name: "Spinner", href: "/components/spinner" },
    { name: "SpotlightCard", href: "/components/spotlight-card" },
    { name: "StatusDot", href: "/components/status-dot" },
    { name: "Switch", href: "/components/switch" },
    { name: "Table", href: "/components/table" },
    { name: "Tabs", href: "/components/tabs" },
    { name: "Tag", href: "/components/tag" },
    { name: "TerminalMockup", href: "/components/terminal-mockup" },
    { name: "TextReveal", href: "/components/text-reveal" },
    { name: "Textarea", href: "/components/textarea" },
    { name: "TiltCard", href: "/components/tilt-card" },
    { name: "Toast", href: "/components/toast" },
    { name: "Toggle", href: "/components/toggle" },
    { name: "ToggleGroup", href: "/components/toggle-group" },
    { name: "Tooltip", href: "/components/tooltip" },
    { name: "TracingBeam", href: "/components/tracing-beam" },
    { name: "TrueFocus", href: "/components/true-focus" },
    { name: "TypingAnimation", href: "/components/typing-animation" },
  ],
};
